auxiliary_data_dir: /mnt/lustre01/pf/b/b380506/work/auxiliary_data
input_files:
- /scratch/b/b380506/ESACCISST_test/recipe_example_20200701_082257/preproc/diag_timeseries_temperature/timeseries_variable/metadata.yml
log_level: info
output_file_type: png
plot_dir: /scratch/b/b380506/ESACCISST_test/recipe_example_20200701_082257/plots/diag_timeseries_temperature/timeseries_diag
profile_diagnostic: false
recipe: recipe_example.yml
run_dir: /scratch/b/b380506/ESACCISST_test/recipe_example_20200701_082257/run/diag_timeseries_temperature/timeseries_diag
script: timeseries_diag
version: 2.0.0b9
work_dir: /scratch/b/b380506/ESACCISST_test/recipe_example_20200701_082257/work/diag_timeseries_temperature/timeseries_diag
write_netcdf: true
write_plots: true
